### ISSUE TITLE
Performance issues with ~20k policies

### ISSUE THREAD

**Issue by MPiccinato** [casbin/node-casbin#90] opened 2019-10-15 16:42 UTC
Was wondering if anyone else is experiencing a slow down even with a relatively low number of policies. 

For our ~20k policies we notice it takes around 5 seconds to evaluate them.

Here is our conf.

```ini
[request_definition]
r = type, resourceId, userId, action

[policy_definition]
p = type, resourceId, userId, action

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.type == p.type && r.resourceId == p.resourceId && r.userId == p.userId && r.action == p.action
```

We have seemed to narrowed it down to [this line in `coreEnforcer.ts`](https://github.com/casbin/node-casbin/blob/ce5082ca9a755ac68b821c32feda5e500e0fb8d6/src/coreEnforcer.ts#L307)

Switching from `compileAsync` to `compile` and removing the `await` brought us down to around 40ms with the same amount of policies.

**Comment by hsluoyz** [comment] 2019-10-16 00:35
@nodece , can we remove `await` as the whole `enforce()` function is `async`?

@MPiccinato if you remove it, then the whole `enforce()` function will not be `async` any more. did you encounter any error about it?

**Comment by MPiccinato** [comment] 2019-10-16 18:31
@hsluoyz We didn't encounter an error when using `compile` instead of `compileAsync` and then removing the async/await nature of the `enforce()` function.

I am assuming here...but I assume it was implemented with an async/await since it could have been possible that one of the functions from the model would be async?

**Comment by MPiccinato** [comment] 2019-10-18 18:51
Here is a fork and PR that we were looking at using to address the issue.

https://github.com/JustSift/node-casbin/pull/1

However, we noticed a few tests are now failing. We are going to look into it a little further but was wondering if anyone here might be able to give a quick look at it.

**Comment by hsluoyz** [comment] 2019-10-19 03:23
@MPiccinato @nodece , I think maybe caching the expression can speed up better. I made a PR: https://github.com/casbin/node-casbin/pull/91 but it's not working. I'm not a JS expert, can anyone help me fix my error?

**Comment by nodece** [comment] 2019-10-19 06:27
@MPiccinato Can you provide the node version?

**Comment by nodece** [comment] 2019-10-19 06:34
@MPiccinato Can you provide the Node.js and node-casbin version?

**Comment by dreamdevil00** [comment] 2019-10-19 09:39
Maybe it's better to introduce a new api called `enforceAsync` for expressions that include async  operations and `enforceSync` for expressions that includes only sync operations. 
For backwards compatity, the behaviour of  current `enforce` api is the same as `enforceAsync`.
What's your thoughts, @hsluoyz

**Comment by nodece** [comment] 2019-10-19 09:48
@dreamdevil00 When use `RBAC` model, `Enforce()` is not working. Because the `RoleManager` interface provides some async function.

**Comment by nodece** [comment] 2019-10-19 10:07
The testbed is: `Macbook Pro(Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz)`

Log: `Execution time (hr): 0.15s 3.81765945ms`

```javascript
const e = await newEnforcer('model.conf', 'policy.csv');

for (let i = 0; i < 50000; i++) {
  let id = i.toString();
  await e.addPolicy('admin', id, id, 'read');
}

const hrstart = process.hrtime();
for (let i = 0; i < 20; i++) {
  await e.enforce('admin', '0', '0', 'write');
}
const hrend = process.hrtime(hrstart);

console.info('Execution time (hr): %ds %dms', hrend[0] / 20, hrend[1] / 1000000 / 20.0);
```

**Comment by rbickham11** [comment] 2019-10-19 16:08
@nodece 
Node `12.10.0` (also seeing the issues in 12.2 in our deployments)
node-casbin `3.0.4`

**Comment by hsluoyz** [comment] 2019-10-19 23:55
> Maybe it's better to introduce a new api called enforceAsync for expressions that include async operations and enforceSync for expressions that include only sync operations.
For backwards compatity, the behaviour of current enforce api is the same as enforceAsync.
What's your thoughts,

@nodece is this OK?

**Comment by nodece** [comment] 2019-10-20 09:04
> > Maybe it's better to introduce a new api called enforceAsync for expressions that include async operations and enforceSync for expressions that include only sync operations.
> > For backwards compatity, the behaviour of current enforce api is the same as enforceAsync.
> > What's your thoughts,
> 
> @nodece is this OK?

https://github.com/casbin/node-casbin/issues/90#issuecomment-544121834

**Comment by nodece** [comment] 2019-10-20 09:53
@rbickham11 
I can not found performance issue.
5000 policies only need 0.15 seconds in my system.

**Comment by hsluoyz** [comment] 2019-10-21 00:58
@MPiccinato

**Comment by rbickham11** [comment] 2019-10-21 14:35
@nodece 

Here is a script that replicates the issue (files attached)
[casbintest.zip](https://github.com/casbin/node-casbin/files/3751359/casbintest.zip)
:

```
const casbin = require('casbin');
	
const enforcer = await casbin.newEnforcer('acl.conf', policies_anonymized.csv');

const hrstart = process.hrtime();
await enforcer.enforce(
  'person-list',
  'dc3da12f-a7ce-4b50-be14-ad5ef3ab584e',
  '2be28594-e29b-491d-ab9e-42a4491209b1',
  'read'
);
  const hrend = process.hrtime(hrstart);

  console.info('Execution time (hr): %ds %dms', hrend[0], hrend[1] / 1000000);
```

`Execution time (hr): 3s 542.650945ms`

Is there a reason you were dividing by 20 in your example? The method returns second and nanosecond parts according to the docs: https://nodejs.org/api/process.html#process_process_hrtime_time

Also just by timing in my head it definitely takes around this time.

**Comment by nodece** [comment] 2019-10-21 14:53
@rbickham11 
Thank for the test file you provided! I need  some time!

Dividing by 20 is the average time, it did 20 times `enforce()`.

**Comment by rbickham11** [comment] 2019-10-21 14:59
@nodece When running this as a more isolated script rather than debugging it inside of our codebase it seems to be much faster. Getting around 100ms times. I'll continue to investigate also, but we've never really seen anything like this before, so it's really strange to me. Sorry for the confusion

**Comment by rbickham11** [comment] 2019-10-21 15:17
@nodece @MPiccinato Not sure if this can lead to anything useful, but when debugging this in vscode in an isolated place it takes a long time, where when just running it directly without debugging, it does not. The difference is a massive 3.5s -> 100ms. If I click continue on that breakpoint it does actually take 3.5s to get to the following breakpoint. I would normally be fine just attributing this to vscode weirdness or something, but we are definitely also seeing the behavior when not debugging in our actual app. 

![image](https://user-images.githubusercontent.com/3526744/67218295-2764d480-f3f4-11e9-8940-ecc6b9f7f2af.png)

**Comment by nodece** [comment] 2019-10-21 15:27
@rbickham11 

In debug model, Casbin needs 3-6s.

Please reopen the issue if you have any problem!

**Comment by rbickham11** [comment] 2019-10-21 15:40
@nodece Our enforcements are still taking ~3.5s inside of our app without debugging. I was just providing the debugging context for the isolated script in case that could be useful for attributing this to other potential causes. Are you saying that it's expected for the enforcements to take 3-6s while debugging?

**Comment by nodece** [comment] 2019-10-22 00:36
@rbickham11 When with debugging，I expected for the enforcements to take 3-6s. Can you help me to reproduce with debugging？

**Comment by hsluoyz** [comment] 2019-10-26 01:50
> Maybe it's better to introduce a new api called `enforceAsync` for expressions that include async operations and `enforceSync` for expressions that include only sync operations.
> For backwards compatity, the behaviour of current `enforce` api is the same as `enforceAsync`.
> What's your thoughts, @hsluoyz

I think @dreamdevil00 's solution is good. We can add a new function maybe called `enforceSync()`. The existing `enforce()` will not be changed. So we don't need to debate which one is better.

Keep in mind to share most of the code between two functions.

Does it sound OK to you all?

**Comment by dreamdevil00** [comment] 2019-10-26 03:22
As for `expression-eval`, in current implementation, there's no way to distinguish between sync  and async calculation, so `compileAsync` regargds any part of the expression as asynchrounous calculation even if the part is synchrounous, this is a major performance hit.

**Comment by nodece** [comment] 2019-10-26 05:33
@hsluoyz, I think @dreamdevil00 provide the solution is good. But in Casbin, If `matcher` has async function and using `compile` , the `enforce` doest not provide the correct result.

**Comment by nodece** [comment] 2019-10-29 13:33
Hi @rbickham11 @dreamdevil00 @MPiccinato I added a `enforceWithSyncCompile()` for it : casbin#96

**Comment by hsluoyz** [comment] 2019-10-29 13:36
Merged: https://github.com/casbin/node-casbin/pull/96

**Comment by hsluoyz** [comment] 2019-10-29 13:36
Closed as resolved.

**Closed by hsluoyz** 2019-10-29 13:36 UTC
Labels: enhancement

**Comment by nodece** [comment] 2019-10-29 13:54
`v3.0.5` has been published to npm. 
Use `enforceWithSyncCompile` instead of `enforce`.
